#!/bin/bash

if [[ -z `which autopilot3` ]]; then
  echo "Autopilot3 is not installed. Skip"
  exit
fi

SCRIPTPATH=`dirname $0`
pushd ${SCRIPTPATH}
autopilot3 run ubuntu_clock_app
retcode=$?
popd
exit $retcode
